import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension

    // Opacity

    // Opacity
    public static let opacityOpacity0 = 0 
    public static let opacityOpacity10 = 0 
    public static let opacityOpacity20 = 0 
    public static let opacityOpacity30 = 0 
    public static let opacityOpacity40 = 0 
    public static let opacityOpacity50 = 1 
    public static let opacityOpacity60 = 1 
    public static let opacityOpacity70 = 1 
    public static let opacityOpacity80 = 1 
    public static let opacityOpacity90 = 1 
    public static let opacityOpacity100 = 1 

    // Size

    // Sizing
    public static let sizeSizing00 = 0 
    public static let sizeSizing05 = 2 
    public static let sizeSizing10 = 4 
    public static let sizeSizing20 = 8 
    public static let sizeSizing30 = 12 
    public static let sizeSizing40 = 16 
    public static let sizeSizing50 = 20 
    public static let sizeSizing60 = 24 
    public static let sizeSizing70 = 32 
    public static let sizeSizing80 = 40 
    public static let sizeSizing90 = 48 
    public static let sizeSizing100 = 64 
    public static let sizeSizing110 = 80 
    public static let sizeSizing120 = 120 
    public static let sizeSizing130 = 160 

    // Space
    public static let space00 = 0 
    public static let space10 = 4 
    public static let space20 = 8 
    public static let space30 = 12 
    public static let space40 = 16 
    public static let space50 = 20 
    public static let space60 = 24 
    public static let space70 = 32 
    public static let space80 = 40 
    public static let space90 = 48 
    public static let space100 = 64 
    public static let space110 = 80 
    public static let space120 = 120 
    public static let space130 = 160 

    // Space
    public static let spaceSpace00 = 0 
    public static let spaceSpace10 = 4 
    public static let spaceSpace20 = 8 
    public static let spaceSpace30 = 12 
    public static let spaceSpace40 = 16 
    public static let spaceSpace50 = 20 
    public static let spaceSpace60 = 24 
    public static let spaceSpace70 = 32 
    public static let spaceSpace80 = 40 
    public static let spaceSpace90 = 48 
    public static let spaceSpace100 = 64 
    public static let spaceSpace110 = 80 
    public static let spaceSpace120 = 120 
    public static let spaceSpace130 = 160 

    // Font Size

    // Font Size
    public static let fontSizeFontSize10 = 12 
    public static let fontSizeFontSize20 = 14 
    public static let fontSizeFontSize30 = 16 
    public static let fontSizeFontSize40 = 18 
    public static let fontSizeFontSize50 = 20 
    public static let fontSizeFontSize60 = 24 
    public static let fontSizeFontSize70 = 28 
    public static let fontSizeFontSize80 = 32 
    public static let fontSizeFontSize90 = 40 
    public static let fontSizeFontSize100 = 48 
    public static let fontSizeFontSize110 = 68 

    // Line Height

    // Line Height
    public static let lineHeightLineHeight10 = 16 
    public static let lineHeightLineHeight20 = 20 
    public static let lineHeightLineHeight30 = 24 
    public static let lineHeightLineHeight40 = 28 
    public static let lineHeightLineHeight50 = 28 
    public static let lineHeightLineHeight60 = 32 
    public static let lineHeightLineHeight70 = 36 
    public static let lineHeightLineHeight80 = 44 
    public static let lineHeightLineHeight90 = 52 
    public static let lineHeightLineHeight100 = 56 
    public static let lineHeightLineHeight110 = 80 

    // Border Width

    // Width
    public static let borderWidthWidth00 = 0 
    public static let borderWidthWidth10 = 1 
    public static let borderWidthWidth20 = 2 
    public static let borderWidthWidth30 = 4 

    // Border Width
    public static let borderWidthBorderWidth00 = 0 
    public static let borderWidthBorderWidth10 = 1 
    public static let borderWidthBorderWidth20 = 2 
    public static let borderWidthBorderWidth30 = 4 

    // Border Radius

    // Border Radius
    public static let borderRadiusBorderRadiusDefault = 12 
    public static let borderRadiusBorderRadiusPill = 80 
    public static let borderRadiusBorderRadiusFull = 160 
    public static let borderRadiusBorderRadius00 = 0 
    public static let borderRadiusBorderRadius05 = 2 
    public static let borderRadiusBorderRadius10 = 4 
    public static let borderRadiusBorderRadius20 = 8 
    public static let borderRadiusBorderRadius30 = 12 
    public static let borderRadiusBorderRadius40 = 16 
    public static let borderRadiusBorderRadius45 = 20 
    public static let borderRadiusBorderRadius50 = 24 
    public static let borderRadiusBorderRadius60 = 32 
}