import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension

    // Opacity

    // Opacity
    public static let opacityOpacity0 = 0 
    public static let opacityOpacity10 = 0 
    public static let opacityOpacity20 = 0 
    public static let opacityOpacity30 = 0 
    public static let opacityOpacity40 = 0 
    public static let opacityOpacity50 = 1 
    public static let opacityOpacity60 = 1 
    public static let opacityOpacity70 = 1 
    public static let opacityOpacity80 = 1 
    public static let opacityOpacity90 = 1 
    public static let opacityOpacity100 = 1 

    // Size

    // Sizing
    public static let sizeSizing00 = 0 
    public static let sizeSizing05 = 2 
    public static let sizeSizing10 = 4 
    public static let sizeSizing20 = 8 
    public static let sizeSizing30 = 12 
    public static let sizeSizing40 = 16 
    public static let sizeSizing50 = 20 
    public static let sizeSizing60 = 24 
    public static let sizeSizing70 = 32 
    public static let sizeSizing80 = 40 
    public static let sizeSizing90 = 48 
    public static let sizeSizing100 = 64 
    public static let sizeSizing110 = 80 
    public static let sizeSizing120 = 120 
    public static let sizeSizing130 = 160 

    // Space

    // Space
    public static let spaceSpace00 = 0 
    public static let spaceSpace10 = 4 
    public static let spaceSpace20 = 8 
    public static let spaceSpace30 = 12 
    public static let spaceSpace40 = 16 
    public static let spaceSpace50 = 20 
    public static let spaceSpace60 = 24 
    public static let spaceSpace70 = 32 
    public static let spaceSpace80 = 40 
    public static let spaceSpace90 = 48 
    public static let spaceSpace100 = 64 
    public static let spaceSpace110 = 80 
    public static let spaceSpace120 = 120 
    public static let spaceSpace130 = 160 

    // Border Width

    // Border Width
    public static let borderWidthBorderWidth00 = 0 
    public static let borderWidthBorderWidth10 = 1 
    public static let borderWidthBorderWidth20 = 2 
    public static let borderWidthBorderWidth30 = 4 

    // Border Radius

    // Border Radius
    public static let borderRadiusBorderRadiusDefault = 12 
    public static let borderRadiusBorderRadiusPill = 80 
    public static let borderRadiusBorderRadiusFull = 160 
    public static let borderRadiusBorderRadius00 = 0 
    public static let borderRadiusBorderRadius05 = 2 
    public static let borderRadiusBorderRadius10 = 4 
    public static let borderRadiusBorderRadius20 = 8 
    public static let borderRadiusBorderRadius30 = 12 
    public static let borderRadiusBorderRadius40 = 16 
    public static let borderRadiusBorderRadius45 = 20 
    public static let borderRadiusBorderRadius50 = 24 
    public static let borderRadiusBorderRadius60 = 32 
}