import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    // Typography

    func textStyleTypographyDisplay01() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 48))
            .textCase(.uppercase) 
    }

    /// Huge headlines
    func textStyleTypographyHeadng01() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 68))
    }

    func textStyleTypographyHeading02() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 47))
    }

    func textStyleTypographyHeading03() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 33))
    }

    func textStyleTypographyHeading04() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 24))
    }

    func textStyleTypographyHeading05() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 20))
    }

    func textStyleTypographyHeading06() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 16))
    }

    func textStyleTypographySubtitle01() -> some View {
        return self
            .font(Font.custom("Inter-600", size: 18))
    }

    func textStyleTypographySubtitle02() -> some View {
        return self
            .font(Font.custom("Inter-600", size: 14))
    }

    func textStyleTypographyBody01() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 18))
    }

    func textStyleTypographyBody02() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 14))
    }

    func textStyleTypographyLabelOverline() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 14))
            .textCase(.uppercase) 
    }

    func textStyleTypographyLabelButton() -> some View {
        return self
            .font(Font.custom("Inter-600", size: 14))
    }

    func textStyleTypographyMetaCaption() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 14))
    }

    func textStyleTypographyMetaAnnotation() -> some View {
        return self
            .font(Font.custom("Inter-600", size: 12))
    }

    func textStyleTypographyFormLabel() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 12))
    }

    func textStyleTypographyFormBody() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 14))
    }

    func textStyleTypographyFormHelper() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 14))
    }

    func textStyleTypographyDisplay02() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 32))
            .textCase(.uppercase) 
    }

    func textStyleTypographyDisplay03() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 28))
            .textCase(.uppercase) 
    }
}
