import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    // Typography

    /// Huge headlines
    func textStyleTypographyH1() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 68))
    }

    func textStyleTypographyH2() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 47))
    }

    func textStyleTypographyH3() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 33))
    }

    func textStyleTypographyH4() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 24))
    }

    func textStyleTypographyH5() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 20))
    }

    func textStyleTypographyH6() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 16))
    }

    func textStyleTypographyLabel() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 14))
            .textCase(.uppercase) 
    }

    func textStyleTypographySubtitle01() -> some View {
        return self
            .font(Font.custom("Inter-600", size: 18))
    }

    func textStyleTypographySubtitle02() -> some View {
        return self
            .font(Font.custom("Inter-600", size: 14))
    }

    func textStyleTypographyBody01() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 18))
    }

    func textStyleTypographyBody02() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 14))
    }

    func textStyleTypographyButton() -> some View {
        return self
            .font(Font.custom("Inter-600", size: 14))
    }

    func textStyleTypographyCaption() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 14))
    }

    func textStyleTypographyAnnotation() -> some View {
        return self
            .font(Font.custom("Inter-600", size: 12))
    }

    func textStyleTypographyHelper() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 14))
    }

    func textStyleTypographyInputLabel() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 10))
    }

    func textStyleTypographyInputText() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 14))
    }
}
