import SwiftUI

// Generated by Supernova - do not modify manually
public extension Gradient {
    
    static let Token = Gradient.TokenGradient()
    
    struct TokenGradient {

        // Colour

        // Gradient

        public let colourGradientHeavy = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 29/255, green: 29/255, blue: 27/255, opacity: 0), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 29/255, green: 29/255, blue: 27/255, opacity: 0.6), location: 0.5),
                Gradient.Stop(color: Color(.sRGB, red: 29/255, green: 29/255, blue: 27/255, opacity: 0.8), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.5, y: 0),
            endPoint: UnitPoint(x: 0.5, y: 1) 
        )

        public let colourGradientMedium = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 29/255, green: 29/255, blue: 27/255, opacity: 0.2), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 29/255, green: 29/255, blue: 27/255, opacity: 0), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.5, y: 0),
            endPoint: UnitPoint(x: 0.5, y: 1) 
        )

        public let colourGradientLoading = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 29/255, green: 29/255, blue: 27/255, opacity: 0), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 29/255, green: 29/255, blue: 27/255, opacity: 0.3), location: 1),
            ]),
            startPoint: UnitPoint(x: 0, y: 0.5),
            endPoint: UnitPoint(x: 1, y: 0.5) 
        )
    }
}