import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    // Shadow

    // Dark

    func shadowShadowDarkShadow01() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.24), radius: 4, x: 0, y: 2) 
    }

    func shadowShadowDarkShadow02() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.24), radius: 8, x: 0, y: 3) 
    }

    func shadowShadowDarkShadow03() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.24), radius: 12, x: 0, y: 4) 
    }

    func shadowShadowDarkShadow032() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.16), radius: 4, x: 0, y: 4) 
    }

    // Light

    func shadowShadowLightShadow03() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.12), radius: 12, x: 0, y: 4) 
    }

    func shadowShadowLightShadow032() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.08), radius: 4, x: 0, y: 4) 
    }

    func shadowShadowLightShadow02() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.12), radius: 8, x: 0, y: 3) 
    }

    func shadowShadowLightShadow01() -> some View {
        return self.shadow(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.12), radius: 4, x: 0, y: 2) 
    }
}